### ISSUE TITLE
[cfn:template-show] Show the template body

### ISSUE THREAD

**Issue by ktheory** [cogcmd/aws-cfn#19]
Currently, `cfn:template-show` shows some high-level info about the template, and a link to the full body.

It'd be nice to be able to see the full body of the template in Slack (either as an option, or by default). Since the link usually goes to a private S3 URL, it's not particularly helpful.

Also, there's an unexpected `title_link` field in the template. Is that intended?

**Comment by mpeck** [comment]
Looks like there was a naming bug in the attachment tag. That's why you are seeing the erroneous `title_link` field.
