### ISSUE TITLE
Dangling "Homepage" reference in README

### ISSUE THREAD

**Issue by doismellburning** [cogcmd/aws-cfn#45]
https://github.com/cogcmd/aws-cfn/blob/7e9439ce9ad80a33242ac234a59d379762938da3/README.md#configuration

> Detailed instructions for configuring this access are available in the README in the GitHub repository located at the URL specified in the Homepage section below.

Alas there is no homepage section below!

**Comment by imbriaco** [comment]
Thanks for the heads up, this is fixed. That README file actually _is_ the homepage. Our copy got ahead of our pasta. ;)
